### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by efsane14010** [kancotdiq/ipcs#15]
[ 1 ] Italy
  [ 2 ] Indonesia                                 [ 3 ] Japan                                     [ 4 ] United States
  [ 5 ] France
  [ 6 ] Korea                                     [ 7 ] German                                    [ 8 ] Turkey                                    [ 9 ] Exit                                                                                    [ Select@Number ]> 5                            Traceback (most recent call last):
  File "scan.py", line 79, in <module>
    main()
  File "scan.py", line 50, in main
    filtering(select)
  File "scan.py", line 64, in filtering
    france()
  File "/data/data/com.termux/files/home/ipcs/LIST/fr.py", line 23, in france
    res = requests.get('https://www.insecam.org/en/bycountry/FR/', headers=headers)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.insecam.org', port=443): Max retries exceeded with url: /en/bycountry/FR/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x713f24db10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by Alyami9110** [comment]
> [1] إيطاليا
> [2] إندونيسيا [3] اليابان [4] الولايات المتحدة
> [5] فرنسا
> [6] كوريا [7] الألمانية [8] تركيا [9] خروج [حدد رقم @]> 5 التتبع (آخر مكالمة أخيرة ):
> ملف "scan.py" ، السطر 79 ، في
> ()
> ملف "scan.py" الرئيسي ، السطر 50 ، في
> التصفية الرئيسية (حدد)
> ملف "scan.py" ، السطر 64 ، في تصفية
> فرنسا ()
> ملف "/ data / data / com.termux / files / home / ipcs / LIST / fr.py "، السطر 23 ، في فرنسا
> res = الطلبات.يحصل('https://www.insecam.org/en/bycountry/FR/ '، headers = headers)
> File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api .py "، السطر 75 ، في
> طلب الإرجاع ('get' ، url ، params = params ، ** kwargs ،
> ملف" /data/data/com.termux/files/usr/lib/python2.7/site-packages /requests/api.py "، السطر 61 ، في طلب
> إرجاع session.request (طريقة = طريقة ، url = url ، ** kwargs)
> ملف" /data/data/com.termux/files/usr/lib/python2.7 /site-packages/requests/sessions.py "، السطر 529 ، في الطلب
> resp = self.send (الإعدادية ، ** send_kwargs)
> ملف" /data/data/com.termux/files/usr/lib/python2.7/ site-packs / applications / Session.py "، السطر 645 ، في الإرسال
> r = adaptor.send (request ، ** kwargs)
> ملف "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py" ، السطر 519 ، في إرسال طلبات
> الاستثناءات
> . ConnectionError: HTTPSConnectionPool (host = 'www.insecam.org'، port = 443): تم تجاوز الحد الأقصى لإعادة المحاولات بعنوان url: / en / bycountry / FR / (سببها NewConnectionError ('<urllib3.connection.HTTPSConnection object at 0x713f24db10>: Failed) لإنشاء اتصال جديد: [Errno 111] تم رفض الاتصال '،))

**Comment by Alyami9110** [comment]
1
